### PR TITLE
feat: respect system first day of week for alarms

### LINKED ISSUE #215: Alarm should follow first day of week setting
### Steps to reproduce

photo_5393349120200135205_y

Here's a solution how to get it: https://stackoverflow.com/a/52365698
Also, I think on Android 13 or 14, there a specific setting for that in the OS settings.

### Expected behavior

Should show Monday for European locales and Sunday for the US.

### Actual behavior

Always shows Sunday as 1st day of week.

### Clock You version

6.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #215

### CODE REVIEW

**Comment by SuhasDissa** [comment]
This doesn't work properly. First day of the week stays same (as Sunday).
image

**Comment by Bnyro** [comment]
Well, it uses the default start of the week by the locale used. It properly sets the start of the week to Monday on my device (German)

**Comment by SuhasDissa** [comment]
> Well, it uses the default start of the week by the locale used. It properly sets the start of the week to Monday on my device (German)

This is working properly and uses whatever the day I set in the settings
```kotlin
val calendar = GregorianCalendar()
val firstDayIndex = calendar.firstDayOfWeek - 1
...
```

**Comment by Bnyro** [comment]
Damn, I wanted to merge the other PR...

**Pull request merged**
