### PR TITLE
refactor: use large rounde FAB for major stopwatch actions

### LINKED ISSUE #178: Increase button size / Change button shape
### Describe your suggested feature

Increase the size and shape of buttons. This not only increases usability, but also follows the look of the material 3 guidelines. Google's apps are all about big and accessable buttons, which looks pretty good.

### Other details

The buttons right now are quite small. They also have color differences, but size differences would be more intuitive. For example: The middle button could be bigger than the left and right one (maybe even in circular shape).
The same goes for the floating action buttons.
Screenshot_20230929-102732

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #178

Not sure if that's really a good solution, screenshots below:

Screenshot_20230929-173743_Clock You
Screenshot_20230929-173749_Clock You

### CODE REVIEW

**Comment by M00NJ** [comment]
I wouldn't change the shape because of the guidelines. I also think it looks out of place. Just use the large FAB preset if you want to change it. I tried it when I changed the button colors but didn't like it, because of what it looks like in the second screenshot, but if you want it larger that's what I'd do.

**Comment by SuhasDissa** [comment]
LGTM

**Review by SuhasDissa — APPROVED** [review]

**Review by M00NJ — APPROVED** [review]

**Comment by Bnyro** [comment]
> I wouldn't change the shape because of the guidelines. I also think it looks out of place. Just use the large FAB preset if you want to change it. I tried it when I changed the button colors but didn't like it, because of what it looks like in the second screenshot, but if you want it larger that's what I'd do.
>
In my opinion a large FAB with the edged corners looks a bit too large, the rounded one feels more intuitive to me (and we also do something similar in Record You btw).

**Comment by M00NJ** [comment]
> In my opinion a large FAB with the edged corners looks a bit too large, the rounded one feels more intuitive to me

I like following the guidelines very closely, but if you prefer this look you can go ahead and merge it :)

**Comment by NeuroException** [comment]
I really like how that one turned out 👍

**Pull request merged**
