### PR TITLE
WIP: New Alarm Layout

### LINKED ISSUE #239: Alarm labels are changed to other alarm lables when deleting one
### Steps to reproduce

1) Create 2-3 alarm clocks
2) Assign labels to each of them
3) Delete one of the created alarms

### Expected behavior

When deleting an alarm clock it should also delete the appropriate name and leave the others with the original name

### Actual behavior

When you delete an alarm clock, its name is replaced on another alarm clock

### Clock You version

6.4 (13)

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**
Moved all the clutter from alarm row into a separate alarm settings sheet

- Need more testing ( in both 24 hour and 12 hour formats)

closes #239

### CODE REVIEW

**Review by Bnyro — COMMENTED** [review]
Looks great, only some minor things I noticed when testing:
1. The "Sound" switch can't be disabled for some reason, it always stays enabled.
2. The "Sound" row has a divider between the sound selection menu and the switch, while the "Vibrate" row doesn't. I propose to add the divider to the "Vibrate" row too.
3. The "Label" text field could use the fill width in my opinion - currently there's some free space at the right.
4. The area that can be used for changing the time in the number picker is quite small, I'd suggest to add some horizontal padding to it that also reacts to scroll gestures.

**Comment by SuhasDissa** [comment]
1. Currently there's no way to disable alarm sound. (I'm planning on adding it)
2. In material3 the divider is used to show that the option is clickable ( check the attached screenshot for example), We could add a divider to the vibrate row if we add more vibration patterns
3. 4.This PR is a WIP. I'll fix it eventually

image

**Review by M00NJ — COMMENTED** [review]
I like many of these changes, like hiding the labels when empty and the reordering of the alarm prefs. I don't really like moving it to a separate sheet though. I think having all information on one screen is an advantage and the less navigation is required the better. I also like leaving the alarms expanded to see when they will ring at a glance, which wouldn't be possible anymore and instead require navigating back and forth. AOSP and G-Clock also work with animated visibility, which is the best choice for this use case imo. Performance issues are mostly a problem with compose and will be improved over time. Also I haven't noticed any myself and my device is a four years old mid ranger, so I doubt they're a major inconvenience. I'd be for taking most of these changes and applying them to the alarm cards. I think that would look really nice.

**Comment by SuhasDissa** [comment]
> I also like leaving the alarms expanded to see when they will ring at a glance, which wouldn't be possible anymore and instead require navigating back and forth.

Does this fix the problem?

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
