### PR TITLE
Added a better placeholder icon for alarms screen

### PR DESCRIPTION
**Pull request by SuhasDissa**
The previous icon had a lot of contrast, which grabbed the user's attention, but it served no purpose other than being a placeholder.

| Before | After |
| --- | --- |
|  |  |

Please let me know if you have any suggestions :)

### CODE REVIEW

**Comment by M00NJ** [comment]
I think I'd prefer an analog alarm icon like the one in the navbar. But it definitely looks a lot nicer than before ;)

**Comment by SuhasDissa** [comment]
I thought digital clock would be a better fit for 21st century. Anyway I will try to make an analog clock icon.

**Comment by M00NJ** [comment]
> I thought digital clock would be a better fit for 21st century. Anyway I will try to make an analog clock icon.

If you want it to be digital, that's fine by me!
You did the work, so it's your choice :)

**Comment by SuhasDissa** [comment]
Hi @M00NJ , I hope you like this one :)

**Review by Bnyro — APPROVED** [review]
Looks great!

**Comment by M00NJ** [comment]
I certainly do ;) It looks really nice!

**Comment by M00NJ** [comment]
@SuhasDissa can you merge here or should I?

**Pull request merged**
