### PR TITLE
style: update launcher icons

### PR DESCRIPTION
**Pull request by M00NJ**
@SuhasDissa I took a close look at the PR you made after I added the new icon for VibeYou. I made sure to make all the same changes here as well, so I think we are good to go this time :)

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
(too lazy to test but looks good to me)

**Comment by M00NJ** [comment]
> (too lazy to test but looks good to me)

I tested it :)

**Comment by SuhasDissa** [comment]
@M00NJ The round icon is not needed if it looks visually similar to the normal icon. That's why I removed it in VibeYou

More info [here](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add-to-your-app)

**Comment by M00NJ** [comment]
> @M00NJ The round icon is not needed if it looks visually similar to the normal icon. That's why I removed it in VibeYou

Yes, that's why I removed all the round icons and also removed it from the manifest. Did I miss one?

**Pull request merged**
